### ISSUE TITLE
'llvm/ADT/MapVector.h' file not found

### ISSUE THREAD

**Issue by goog00** [banach-space/llvm-tutor#102]
Description:
First time running this project.
Following the tutorial (https://github.com/banach-space/llvm-tutor#helloworld-your-first-pass), I ran through the HelloWorld Pass.
But I get an exception when running OpcodeCounter.

<img width="1232" alt="image" src="https://github.com/banach-space/llvm-tutor/assets/6683273/faff4e57-ad71-49f3-9985-2b0ce0d712a6">
<img width="1211" alt="image" src="https://github.com/banach-space/llvm-tutor/assets/6683273/a640e8ee-57fe-4661-bde4-6fdd4fde2317">

Steps :

cd /Users/steng/llvm-study/test-llvm-tutor/build
export LLVM_DIR=/usr/local/opt/llvm@16
cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR /Users/steng/llvm-study/llvm-tutor/lib/
make

 

Environment details:

Operating system: macos ventura
LLVM/Clang version: 16.0.6

Thank you for your help!

**Comment by banach-space** [comment]
Hi, thanks for reporting this and sorry that you are hitting this!

Would you mind sharing full CMake log? You can just copy & paste it here. That would be more helpful than a screenshot. Thank you!

**Comment by goog00** [comment]
Thank you very much for your reply, this is CMake log。

CMake Warning:
  Ignoring extra path from command line:

   "/Users/steng/llvm-study/test-llvm-tutor/build/cmake"


CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.26)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.9s)
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   ConvertFCmpEq
   DuplicateBB
   DynamicCallCounter
   FindFCmpEq
   InjectFuncCall
   MBAAdd
   MBASub
   MergeBB
   OpcodeCounter
   RIV
   StaticCallCounter

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    LT_LLVM_INSTALL_DIR


-- Build files have been written to: /Users/steng/llvm-study/test-llvm-tutor/build


If you need any more information, please feel free to let me know。
Thank you very much for your help!

**Comment by goog00** [comment]
Hi, the problem is solved. 

 cmake in difference dir ：

before：cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR /Users/steng/llvm-study/llvm-tutor/**lib**/

after：cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR /Users/steng/llvm-study/llvm-tutor/

I started testing HellWorld successfully, so I followed its process to test OpcodeCounter without looking carefully at CMakeList.txt. I am so sorry, I am a beginner and not very familiar with cmake. 

Thank you very much for your help!

**Comment by banach-space** [comment]
Fantastic, hope you will enjoy the examples!

**Comment by goog00** [comment]
Hi, Thank you I learned a lot from it.
 I found a small problem in the document, you can correct it. There is one more opt, marked in red in the picture.
<img width="1055" alt="image" src="https://github.com/banach-space/llvm-tutor/assets/6683273/493c8e17-6f1c-4bb4-bb44-84649d2bd923">
