### ISSUE TITLE
missing: how to get "opt -analyze --loops" from the new pass manager

### ISSUE THREAD

**Issue by dtkerns** [banach-space/llvm-tutor#107]
related to #50 but I did't want to comment on a closed issue.
I've read thru the official llvm docs and can't figure out how to get [loops: Natural Loop Information](https://llvm.org/docs/Passes.html#loops-natural-loop-information) out of the new pass manager
appreciate any assistance

**Comment by banach-space** [comment]
hey!

The pass is defined here: https://github.com/llvm/llvm-project/blob/17afa5befb4cbe86c22c25ae1603433c8bd21551/llvm/lib/Analysis/LoopInfo.cpp#L1168-L1177. Try `-verify-loop-info`. Also, for generic LLVM stuff, https://discourse.llvm.org/ tends to be better.

**Comment by dtkerns** [comment]
thanks ... but I need a bit more hand-holding than just your link to the .cpp file. I'll post over in the discourse channel, thanks for the link!

**Comment by dtkerns** [comment]
btw, if you can help, I'm still not getting anywhere ... https://discourse.llvm.org/t/need-usage-help-w-new-pass-manager-for-opt-analysis-natural-loop-information/75874

**Comment by dtkerns** [comment]
bjope chashed this down... looks like a bug in `opt`. (see discourse link above)
