### ISSUE TITLE
question about MBAAdd

### ISSUE THREAD

**Issue by qbojj** [banach-space/llvm-tutor#108]
in `MBAAdd.cpp` there is a RNG element:

```c++
// Get a (rather naive) random number generator that will be used to decide
// whether to replace the current instruction or not.
// FIXME We should be using 'Module::createRNG' here instead. However, that
// method requires a pointer to 'Pass' on input and passes
// for the new pass manager _do_not_ inherit from llvm::Pass. In other words,
// 'createRNG' cannot be used here and there's no other way of obtaining
// llvm::RandomNumberGenerator. Last checked for LLVM 8.
std::mt19937_64 RNG;
RNG.seed(1234);
std::uniform_real_distribution<double> Dist(0., 1.);
```

first of all it looks like that it is no longer used, but my question is about the comment.
Cannot something like this be done?

```c++
auto pRNG = BB.getModule()->createRNG("mba-add");
RandomNumberGenerator &RNG = *pRNG;
```

or was `getModule` method just added after LLVM 8?

**Comment by banach-space** [comment]
Cześć Jakub,

Thanks for visiting 👋🏻 Yes, that code is no longer used should be removed. Patches welcome :)

> or was getModule method just added after LLVM 8?

It's been a while, but yes, I vaguely remember waiting for the LLVM bump and then forgetting to fix this. Thanks for spotting and for reporting this!

-Andrzej
