### ISSUE TITLE
Output for test in README fails with expected top-level entity

### ISSUE THREAD

**Issue by kharazit** [banach-space/llvm-tutor#11]
After building the project on Ubuntu with LLVM-10, updated yesterday, I see the following: 
```
cades@kharazi-cades-dev:~/llvm-tutor$ $LLVM_DIR/bin/opt -load-pass-plugin libHelloWorld.dylib -passes=hello-world -disable-output input_for_hello.ll
/home/cades/.llvm/bin/opt: input_for_hello.ll:1:2: error: expected top-level entity
        .text
        ^ 
```

**Comment by banach-space** [comment]
Hi,

Thank you for reporting this! Could you also show me how you generated `input_for_hello.ll`? And perhaps the first 10 lines?

-Andrzej

**Comment by kharazit** [comment]
Ahh, I think I forgot to update after the llvm install. It's all working now. Thanks
