### ISSUE TITLE
This analysis pass was not registered prior to being queried

### ISSUE THREAD

**Issue by NoobCat2000** [banach-space/llvm-tutor#113]
i was testing OpcodeCoutner pass in windows, but the assert failed in line:
```c
auto& OpcodeMap = FAM.getResult<OpcodeCounter>(Func);
```

Delve more deeper, i see it fail in getResult<llvm::PassInstrumentationAnalysis>, maybe PassInstrumentationAnalysis is not loaded. Can someone help me

**Comment by jvstech** [comment]
This is a bug that, for whatever reason, _only_ occurs on Windows.

I get around this by [manually adding `llvm::PassInstrumentationAnalysis` registration](https://github.com/jvstech/vs-windows-llvm/blob/67c76f2edd6fd53d5d254200d515137074f77857/lib/string-analysis.cpp#L74); it seems the fix here would be to add something like this to each of the analysis registrations:

```c++
  auto &MAM = FAM->getResult<ModuleAnalysisManagerFunctionProxy>(F).getManager();
  MAM.registerPass([&] { return PassInstrumentationAnalysis{}; });
```

I haven't taken a solid look at this code in a while, so I can only give this as a rough idea of what needs to be done.

In reality, I think there's an underlying issue with LLVM causing this problem in the first place, but it _can_ be worked around.

**Comment by NoobCat2000** [comment]
> This is a bug that, for whatever reason, _only_ occurs on Windows.
> 
> I get around this by [manually adding `llvm::PassInstrumentationAnalysis` registration](https://github.com/jvstech/vs-windows-llvm/blob/67c76f2edd6fd53d5d254200d515137074f77857/lib/string-analysis.cpp#L74); it seems the fix here would be to add something like this to each of the analysis registrations:
> 
> ```c++
>   auto &MAM = FAM->getResult<ModuleAnalysisManagerFunctionProxy>(F).getManager();
>   MAM.registerPass([&] { return PassInstrumentationAnalysis{}; });
> ```
> 
> I haven't taken a solid look at this code in a while, so I can only give this as a rough idea of what needs to be done.
> 
> In reality, I think there's an underlying issue with LLVM causing this problem in the first place, but it _can_ be worked around.

Its work, you are great, thank you very much
