### ISSUE TITLE
Outdated Dockerfile

### ISSUE THREAD

**Issue by x14ngch3n** [banach-space/llvm-tutor#117]
[Dockerfile_ubuntu](https://github.com/banach-space/llvm-tutor/blob/main/Dockerfile_ubuntu) and [Dockerfile_ubuntu_apt](https://github.com/banach-space/llvm-tutor/blob/main/Dockerfile_ubuntu_apt) can not built successfully because of the version specified in [CMakeLists.txt](https://github.com/banach-space/llvm-tutor/blob/f9ee5e3c032b162b5e4fa3065008a40d8bf12fd7/CMakeLists.txt#L55) and the missing of libzstd-dev.

**Comment by banach-space** [comment]
Thanks! Would you be able to send an update?

**Comment by x14ngch3n** [comment]
Ok, I will do that later

**Comment by x14ngch3n** [comment]
I try to build the arch linux docker but failed at link time, the error messages is as below:

```bash
23.78 FAILED: bin/static 
23.78 : && /usr/sbin/c++ -Wall  -fdiagnostics-color=always -fvisibility-inlines-hidden -g  tools/CMakeFiles/static.dir/StaticMain.cpp.o tools/CMakeFiles/static.dir/__/lib/StaticCallCounter.cpp.o -o bin/static  -lLLVMCore  -lLLVMPasses  -lLLVMIRReader  /usr/lib/libLLVMSupport.a  -lrt  -ldl  -lm  /usr/lib/libz.so  /usr/lib/libzstd.so.1.5.6  /usr/lib/libtinfo.so  /usr/lib/libLLVMDemangle.a && :
23.78 /usr/sbin/ld: cannot find -lLLVMCore: No such file or directory
23.78 /usr/sbin/ld: cannot find -lLLVMPasses: No such file or directory
23.78 /usr/sbin/ld: cannot find -lLLVMIRReader: No such file or directory
23.78 collect2: error: ld returned 1 exit status
23.93 [24/27] Building CXX object lib/CMakeFiles/DuplicateBB.dir/DuplicateBB.cpp.o
23.93 [25/27] Building CXX object lib/CMakeFiles/MBAAdd.dir/MBAAdd.cpp.o
23.93 ninja: build stopped: subcommand failed.
------
Dockerfile_archlinux:47
--------------------
  46 |     # 5. BUILD AND RUN LLVM-TUTOR
  47 | >>> RUN mkdir -p $TUTOR_DIR/build \
  48 | >>>     && cd $TUTOR_DIR/build \
  49 | >>>     && cmake -G Ninja -DLT_LLVM_INSTALL_DIR=$LLVM_DIR ../ \
  50 | >>>     && ninja \
  51 | >>>     && $VENV_DIR/bin/lit test/
  52 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir -p $TUTOR_DIR/build     && cd $TUTOR_DIR/build     && cmake -G Ninja -DLT_LLVM_INSTALL_DIR=$LLVM_DIR ../     && ninja     && $VENV_DIR/bin/lit test/" did not complete successfully: exit code: 1
```

I didn't find libLLVMCore.a on arch linux's system path, do you know how to solve the problem?

**Comment by banach-space** [comment]
Thank you for the investigation and for fixing this! 🙏🏻 

> LLVM is built as shared library on [Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/blob/main/PKGBUILD?ref_type=heads#L89), so we need to link the static executable against libLLVM.so

Would you mind adding this note in the CMake file? Sorry, I should've asked earlier!

**Comment by x14ngch3n** [comment]
I added a `message()` in [CMakeLists.txt](https://github.com/banach-space/llvm-tutor/blob/e9a9cfc52766669db6917b075b34ad7fc7546bcc/tools/CMakeLists.txt#L14) 🤝 🤝 🤝
