### ISSUE TITLE
Failed to load passes from 'libHelloWorld.so'. Request ignored.

### ISSUE THREAD

**Issue by khordadi** [banach-space/llvm-tutor#12]
Hello Andrzej,

I built `HelloWorld` pass on macOS, and it worked fine, but I had a problem on Linux. 

The command I used:
``` bash
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
git checkout release/10.x
mkdir build
cd build

cmake -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 ../llvm
cmake --build .

export LLVM_DIR=$(pwd)

git clone https://github.com/banach-space/llvm-tutor
cd llvm-tutor
export TUTOR_DIR=$(pwd)
cd HelloWorld/
mkdir build
cd build

cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR ../
make

$LLVM_DIR/bin/clang -S -emit-llvm $TUTOR_DIR/inputs/input_for_hello.c -o input_for_hello.ll

$LLVM_DIR/bin/opt -load-pass-plugin libHelloWorld.so -passes=hello-world -disable-output input_for_hello.ll
```

The error from `opt`:
```
Failed to load passes from 'libHelloWorld.so'. Request ignored.
/home/amir/llvm-project/build/bin/opt: unknown pass name 'hello-world'
```

Thanks,
Amir

**Comment by banach-space** [comment]
Hi Amir,

I am sorry that you're hitting this issue! I was not aware of it, so thanks a ton for reporting it and for this very thorough reproducer - that's much appreciated!

Could you try this:
```
$LLVM_DIR/bin/opt -load-pass-plugin ./libHelloWorld.so -passes=hello-world -disable-output input_for_hello.ll
```
That worked for me. I don't quite understand why there would be difference in behavior between Mac OS and Linux. I'll try to dig out something.

Btw, I assume that you also got this with your error message:
```
Could not load library 'libHelloWorld.so': libHelloWorld.so: cannot open shared object file: No such file or directoryStack dump:
```

Thank you,
Andrzej

**Comment by khordadi** [comment]
Andrzej,

No problem at all, and you're very welcome! The llvm-tutor helps me a lot so far, believe me!

Your command solved the problem. I have to use `./libHelloWorld.so` instead of `libHelloWorld.so`!

>Btw, I assume that you also got this with your error message:

No, I didn't! Only the one that I've sent you, which is gone now.

Cheers,
Amir

**Comment by Phantom1003** [comment]
I also meet this problem, thank you very much @banach-space , it is very helpful. 
But I do not got this error:

> Btw, I assume that you also got this with your error message:
Could not load library 'libHelloWorld.so': libHelloWorld.so: cannot open shared object file: No such file or directoryStack dump:

Why this modification works ?

**Comment by banach-space** [comment]
> Why this modification works? 

I've just compared the manual for `dlopen` on Mac OS and Linux (which is what is ultimately used for loading the plugins). On Mac OS there's this section:

>      When path does not contain a slash character (i.e. it is just a leaf name), dlopen() searches the following until it finds a compatible Mach-O file: $LD_LIBRARY_PATH, $DYLD_LIBRARY_PATH, current working directory, $DYLD_FALLBACK_LIBRARY_PATH.

In particular, **current working directory**.  According to the manual on Linux, the current working directory is not considered when searching for libraries. That explains why `libHelloWorld.dylib` is sufficient on Mac OS, but on Linux a directory also has to be specified, i.e. `./libHelloWorld.so`.

> How to get the error you mentioned ?
It's very hard to answer this without having access to your configuration. Perhaps stderr is redirected somewhere (i.e. it's not printed on the screen)? For the record, here's the error that I get:
```
$LLVM_DIR/bin/opt -load-pass-plugin libHelloWorld.so -passes=hello-world -disable-output input_for_hello.ll
Failed to load passes from 'libHelloWorld.so'. Request ignored.
Expected<T> must be checked before access or destruction.
Unchecked Expected<T> contained error:
Could not load library 'libHelloWorld.so': libHelloWorld.so: cannot open shared object file: No such file or directoryStack dump:
```

This is followed by a backtrace, which I skipped.

In any case, thank you both for this, I'll update README so that this is avoided in the future!

**Comment by Phantom1003** [comment]
> > Why this modification works?
> 
> I've just compared the manual for `dlopen` on Mac OS and Linux (which is what is ultimately used for loading the plugins). On Mac OS there's this section:
> 
> > ```
> >  When path does not contain a slash character (i.e. it is just a leaf name), dlopen() searches the following until it finds a compatible Mach-O file: $LD_LIBRARY_PATH, $DYLD_LIBRARY_PATH, current working directory, $DYLD_FALLBACK_LIBRARY_PATH.
> > ```
> 
> In particular, **current working directory**. According to the manual on Linux, the current working directory is not considered when searching for libraries. That explains why `libHelloWorld.dylib` is sufficient on Mac OS, but on Linux a directory also has to be specified, i.e. `./libHelloWorld.so`.
> 
> > How to get the error you mentioned ?
> > It's very hard to answer this without having access to your configuration. Perhaps stderr is redirected somewhere (i.e. it's not printed on the screen)? For the record, here's the error that I get:
> 
> ```
> $LLVM_DIR/bin/opt -load-pass-plugin libHelloWorld.so -passes=hello-world -disable-output input_for_hello.ll
> Failed to load passes from 'libHelloWorld.so'. Request ignored.
> Expected<T> must be checked before access or destruction.
> Unchecked Expected<T> contained error:
> Could not load library 'libHelloWorld.so': libHelloWorld.so: cannot open shared object file: No such file or directoryStack dump:
> ```
> 
> This is followed by a backtrace, which I skipped.
> 
> In any case, thank you both for this, I'll update README so that this is avoided in the future!

Thank you! With a Debug version opt, I got the error message. For the first question, I mean that, if I build a in-tree pass, I can directly load it, but for out-of-tree version we need absolute path :/

**Comment by Phantom1003** [comment]
[Update] there is also another way to fix this problem, add a `message("${LLVM_LIBRARY_DIRS}")` into show your llvm library path, usually it is `<llvm/install/path>/lib`, then you can directly use your pass name

**Comment by banach-space** [comment]
@Phantom1003 

> For the first question, I mean that, if I build a in-tree pass, I can directly load it, but for out-of-tree version we need absolute path :/

That's because of `opt`'s `RUNPATH`:

```
$ readelf -d $LLVM_DIR/bin/opt | head -4

Dynamic section at offset 0x4bd5df0 contains 34 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
```

In other words, `opt` will by default look in `$LLVM_DIR/lib`. If you happen to be in `$LLVM_DIR/lib` then that's also your current working directory, but that doesn't change the fact that the current working directory is not taken into account by `dlopen` on Linux. I hope that his makes sense!
