### ISSUE TITLE
The RIV pass doesn't show anything

### ISSUE THREAD

**Issue by khordadi** [banach-space/llvm-tutor#14]
Hello Andrzej,

I tried `HelloWorld` on macOS, and it works fine. But [RIV](https://github.com/banach-space/llvm-tutor#riv) doesn't show anything.

The commands I used:

``` bash
export LLVM_DIR=/usr/local/opt/llvm
git clone https://github.com/banach-space/llvm-tutor
cd llvm-tutor
export TUTOR_DIR=$(pwd)

mkdir build
cd build
cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR ../
make

$LLVM_DIR/bin/clang -emit-llvm -S -O1 $TUTOR_DIR/inputs/input_for_riv.c -o input_for_riv.ll
$LLVM_DIR/bin/opt -load ./lib/libRIV.dylib -legacy-riv input_for_riv.ll
```
I got this:
```
WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.
```
Then I used `-disable-output`, but got nothing on stdout.
```
$LLVM_DIR/bin/opt -load ./lib/libRIV.dylib -legacy-riv -disable-output input_for_riv.ll
```

I guess there are some problems with pass registration because when I changed the code (using scaffolding codes for pass registration in `HelloWorld`) I was able to make it work.

Thanks.

**Comment by banach-space** [comment]
Hi Amir,

Thank you for reporting this! The documentation is incomplete, that's my bad, sorry! Try with `-analyze`:

```
$LLVM_DIR/bin/opt -load ./lib/libRIV.dylib -legacy-riv -analyze input_for_riv.ll
```
`analyze` is an option in opt (only available for the legacy PM) that means that the [print method](https://llvm.org/docs/WritingAnLLVMPass.html#the-print-method) is called.

I'll update the docs today - sorry that you got stuck on this!

Andrzej

**Comment by khordadi** [comment]
Andrzej,

You're very welcome! That fixed the problem, thank you very much.

Amir
