### ISSUE TITLE
Do we support all kinds of passes ?

### ISSUE THREAD

**Issue by Phantom1003** [banach-space/llvm-tutor#16]
I find that the examples here are used for middle-end pass at IR level, does our framework can be used on backend pass ?

**Comment by banach-space** [comment]
That's correct, **llvm-tutor** contains only middle-end passes, i.e. passes that can be run with [opt](https://llvm.org/docs/CommandGuide/opt.html). 

Backend passes are run with [llc](https://llvm.org/docs/CommandGuide/llc.html) and that's one key difference. Also, when developing a backend pass, how do you decide which backend to target? That's not an issue with middle-end passes, i.e. every pass is relevant for all available backends.

I think that writing some backend passes would be a great idea, but ideally these passes should be as generic as possible. Do you have any suggestions?

**Comment by Phantom1003** [comment]
When people are writing back-end passes, he has already decided on the back-end he wants to use by default, maybe you should cover some common arch, x86, RISC-V, and another problem I'm worry about is that for backend pass, we need to add passes in the LLVM source code to regist, is this possible to build out-of-tree ? Because I don't find a option to load pass in llc. 
I think a demo about prologue/epilogue extension, and nop-insert will be useful to beginner. And some demo for connecting  middle-backend together will be better, like tag some inst in IR, and instrument at MIR.
