### ISSUE TITLE
about DuplicateBB pass , the return value of the run method is not right

### ISSUE THREAD

**Issue by 10ca1h0st** [banach-space/llvm-tutor#19]
In DuplicateBB.cpp, the run method of the DuplicateBB struct return none() when Targets is empty and return all() when Targets is not empty. 
Should the return value be reversed?
Because when Targets is empty the pass dose not modify the LLVM program, the run method should return all()

**Comment by banach-space** [comment]
Good catch, thank you for reporting!

Andrzej
