### ISSUE TITLE
opt: Unknown command line argument '-debug-only=mba-add'.

### ISSUE THREAD

**Issue by khordadi** [banach-space/llvm-tutor#20]
I'm using macOS, and I install LLVM with `brew`.
```
$ llvm-config --version
10.0.0
```

In [debugging](https://github.com/banach-space/llvm-tutor#debugging):

Without `-debug-only=mba-add -stats`:
```bash
opt -load-pass-plugin build/lib/libMBAAdd.dylib -passes=mba-add input_for_mba.ll -S -o input_for_mba.transformed.ll
```
It generates `input_for_mba.transformed.ll` with no error/warning.

However, with `-debug-only=mba-add -stats`:
```bash
opt -load-pass-plugin build/lib/libMBAAdd.dylib -passes=mba-add -debug-only=mba-add -stats input_for_mba.ll -S -o input_for_mba.transformed.ll 
```
Output:
```
opt: Unknown command line argument '-debug-only=mba-add'.  Try: 'opt --help'
opt: Did you mean '--debug-pass=mba-add'?
```
When I used `--debug-pass=mba-add`:
```
opt -load-pass-plugin build/lib/libMBAAdd.dylib -passes=mba-add input_for_mba.ll --debug-pass=mba-add -stats -S -o input_for_mba.transformed.ll 
```
Output:
```
opt: for the --debug-pass option: Cannot find option named 'mba-add'!
```

**Comment by banach-space** [comment]
Hi @khordadi !

Thank you for creating this issue and for being so thorough. `-debug-only` works only for Debug builds. This is documented [here](https://github.com/llvm/llvm-project/blob/254e0abf5be2e98cb7f1fa52617b71f4b94b11a4/llvm/include/llvm/Support/Debug.h#L55-L58). When you install LLVM with `brew` you are getting a Release build instead (there would be no point in distributing a Debug build).

I forgot to mention this in README.md. An update will follow shortly! :) Sorry for the confusion and many thanks for raising this!

Andrzej

**Comment by khordadi** [comment]
Hi Andrzej,

Thank you very much for your response.

It works fine after using `-DCMAKE_BUILD_TYPE=Debug`.

Cheers,
Amir

**Comment by banach-space** [comment]
Just to double check - it does not work with `opt` from `brew`, right? You need to build LLVM from sources in Debug mode (as well as *llvm-tutor*).

**Comment by khordadi** [comment]
Correct, I didn't use `brew`.

I used these commands to build LLVM on my Linux machine:

```
cd llvm-project
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS=clang ../llvm
make -j$(nproc --all)

```

(I have a machine with 256 cores. That's why I was able to build it and write you back so fast.😅 )
