### ISSUE TITLE
Unable to load passes from libHelloWorld.so

### ISSUE THREAD

**Issue by localacct** [banach-space/llvm-tutor#22]
Hi

I have tried the recommended command line from #12 but I am still not able to load the .so file. The command line I used was
````
$LLVM_DIR/bin/opt -load-pass-plugin ./libHelloWorld.so -passes=hello-world -disable-output input_for_helloworld.ll
````

I am running on Ubuntu 2004 LTS in VirtualBox.

$LLVM_DIR/bin/opt --version
LLVM version 12.0.0-test
Optimized build
Default target: x86_64-unknown-linux-gnu
Host CPU: haswell

**Comment by banach-space** [comment]
Hi,

Thank you for using *llvm-tutor* and for reporting this. Could you paste the full error message?

Thank you!

**Comment by localacct** [comment]
Hi

The error message was
````
Failed to load passes from './libHelloWorld.so'. Request ignored.
/home/llvm/build/bin/opt: unknown pass name 'hello-world'.
````

**Comment by banach-space** [comment]
I haven't been able to reproduce it. Could you:
* double check that there's `libHelloWorld.so` in the directory from which you're trying to load the pass?
* paste your build steps (for **llvm-tutor** and LLVM)?

Also, I've just realised that you are using LLVM 12. Currently **llvm-tutor** supports LLVM 11. Could you please test with LLVM 11?

Thanks!

**Comment by localacct** [comment]
Hi

These are some screenshots of the build steps for llvm-tutor
````
cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR ../Helloworld/
````
![image](https://user-images.githubusercontent.com/39975764/99339354-fd186b80-28c0-11eb-8e2a-b07112f58941.png)

````
make
````
![image](https://user-images.githubusercontent.com/39975764/99339398-14efef80-28c1-11eb-92b6-e5b02fb58044.png)
![image](https://user-images.githubusercontent.com/39975764/99339431-21744800-28c1-11eb-8388-3610363be389.png)

**Comment by localacct** [comment]
Hi

I installled precompiled binaries using apt and opt-11 managed to run the command. Perhaps there is something different in the way I built it or maybe because something changed in version 12?
