### ISSUE TITLE
HelloWorld example doesn't show anything

### ISSUE THREAD

**Issue by liusy58** [banach-space/llvm-tutor#34]
Hi, sir, follow the instructions you mentioned in the document, I got nothing in the screen:

```
 2314  echo "export LLVM_DIR=/usr/local/opt/llvm@12" >>  ~/.zshrc
...
 2321  cd build
 2322  cmake -DLT_LLVM_INSTALL_DIR=$LLVM_DIR ../HelloWorld/
 2323  make
 2324  $LLVM_DIR/bin/clang -S -emit-llvm ../inputs/input_for_hello.c -o input_for_hello.ll
 2325  $LLVM_DIR/bin/opt -load-pass-plugin ./libHelloWorld.dylib  -disable-output input_for_hello.ll 
```

**Comment by banach-space** [comment]
Hi @liusy58 ,

Thank you for reporting this and apologies for the confusion. I am aware of this, but haven't had the time to research a proper solution.

Could you refer to https://github.com/banach-space/llvm-tutor/issues/33 for a workaround?

Thank you!

**Comment by liusy58** [comment]
Thx for your reply~

**Comment by banach-space** [comment]
Fixed by https://github.com/banach-space/llvm-tutor/commit/0a588fbb92d689692aecc67d549704ff9e995c8d.

Thanks for reporting!
