### ISSUE TITLE
[OpCodeCounter] Wrong result for functions

### ISSUE THREAD

**Issue by xgupta** [banach-space/llvm-tutor#38]
It is expected : 

=================================================
LLVM-TUTOR: OpcodeCounter results for `main`
=================================================
OPCODE               #N TIMES USED
-------------------------------------------------
load                 2
br                   4
icmp                 1
add                  1
ret                  1
alloca               2
store                4
call                 4
-------------------------------------------------

What is happening:

Printing analysis 'OpcodeCounter Pass' for function 'main':
=================================================
LLVM-TUTOR: OpcodeCounter results
=================================================
OPCODE               #TIMES USED
-------------------------------------------------
ret                  1         
-------------------------------------------------

I think main should print all instructions opcodes.

$LLVM_DIR/bin/opt --version

LLVM (http://llvm.org/):
  LLVM version 12.0.0
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: bdver4

**Comment by banach-space** [comment]
Thank you for testing and reporting this @xgupta , that's very much appreciated! I've just pushed a patch that should fix this (and GitHub closed this issue automatically). Please feel free to re-open if you are still seeing incorrect results.

Best regards,
-Andrzej
