### ISSUE TITLE
[InjectFuncCall] Getting compilation error while running InjectFuncCall with opt

### ISSUE THREAD

**Issue by xgupta** [banach-space/llvm-tutor#39]
Please see the attached screenshot : 
![newerorrrr](https://user-images.githubusercontent.com/72094336/125328097-89503500-e361-11eb-81b3-4e484e79ebe3.png)

**Comment by xgupta** [comment]
DynamicCallCounter also facing the similar problem.

**Comment by banach-space** [comment]
This was closed by accident. I will look into this tomorrow.

**Comment by banach-space** [comment]
Hi @xgupta , I've not been able to reproduce this. Could you paste a textual version of your input file? You can generate it like this:
```
$LLVM_DIR/bin/clang -O1 -emit-llvm -S -c ../inputs/input_for_hello.c -o input_for_hello.ll
```

Thanks!

**Comment by xgupta** [comment]
oh, thanks @banach-space for looking into it. Here is the input_for_hello.ll
https://gist.github.com/84b3aaf69dac9a2ee432b55181feb997

**Comment by banach-space** [comment]
Still no luck, that input file looks totally fine to me. I'm a bit puzzled by the output that you are getting - why does it complain about `noundef` or `nocallback`? `InjectFuncCall` does not add these 🤔 . Have you made any modifications to the pass? From what I can see, you are using LLVM provided with Arch Linux, right? I could try setting-up a docker with that.

With all of the CI being 🟢 , I'm not sure how to move this forward.

**Comment by xgupta** [comment]
Oh that is the case. No problem I will do some investigation on my side.

And yes I using arch Linux and I didn't make any changes to the pass.
I think we can close this issue for now.
-shivam 
 
  On Sat, Jul 24, 2021 at 8:22 PM, Andrzej ***@***.***> wrote:   


Still no luck, that input file looks totally fine to me. I'm a bit puzzled by the output that you are getting - why does it complain about noundef or nocallback? InjectFuncCall does not add these 🤔 . Have you made any modifications to the pass? From what I can see, you are using LLVM provided with Arch Linux, right? I could try setting-up a docker with that.

With all of the CI being 🟢 , I'm not sure how to move this forward.

**Comment by banach-space** [comment]
I will try testing on Arch Linux first. Please bear with me :)

**Comment by banach-space** [comment]
Hi @xgupta 

I added a Docker config file for Arch Linux and tested that in GitHub CI: https://github.com/banach-space/llvm-tutor/runs/3183476323?check_suite_focus=true. It's 🟢.

Everything seems fine from **llvm-tutor** perspective, so I've closed this. Please re-open if it's still broken for you and there's a way for me to reproduce this.

Thanks again for bringing this up!
