### ISSUE TITLE
Missing "Run the pass through opt - New PM" for InjectFuncCall

### ISSUE THREAD

**Issue by FantasqueX** [banach-space/llvm-tutor#50]
I noticed that the instruction for "Run the pass through opt - New PM" in section InjectFuncCall is missing. And I tried  as following, it worked. So I suggested to add this instruction to README.md

`$LLVM_DIR/bin/opt -load-pass-plugin <build_dir>/lib/libInjectFuncCall.so --passes="inject-func-call" input_for_hello.bc -o instrumented.bin`

**Comment by banach-space** [comment]
Thank you for bringing this up! In fact, other examples are missing instructions for the new PM too. And with the legacy PM being potentially [deprecated](https://lists.llvm.org/pipermail/llvm-dev/2021-August/152305.html) soon, a few sections will require updating as well (e.g. https://github.com/banach-space/llvm-tutor#about-pass-managers-in-llvm).

Your suggestion makes sense to me. I can take care of the other bits in due time. Btw, I won’t have access to my workstation in the coming week, so won’t be able to review sooner than early Sept.

Many thanks for all your help!

-Andrzej

**Comment by FantasqueX** [comment]
Sorry for no response for so long, since I was too busy these days. I have read the [thread ](https://lists.llvm.org/pipermail/llvm-dev/2021-August/152305.html)which you mentioned. As LLVM plans to remove legacy PM in ver 14, there will be a not short period of time when the two pm coexist. So should I create a PR to upgrade README.md to add some missing instructions for new PM @banach-space ?
