### ISSUE TITLE
Possible issue with optimization for the InjectFuncCall part

### ISSUE THREAD

**Issue by mantador** [banach-space/llvm-tutor#53]
I'm using LLVM compiled from branch `release/13.x` with the new Pass Manager.

After following the steps at the [InjectFuncCall section](https://github.com/banach-space/llvm-tutor#injectfunccall) when i run 
`$LLVM_DIR/bin/lli instrumented_hello.bin` 
I only get the following output

> (llvm-tutor) Hello from: main
> (llvm-tutor)   number of arguments: 2

I tried by removing `-O1` option when compiling with clang-13 and it shows the correct output.

I'd open a pr but since I'm a beginner with compilers and llvm I'm not sure if there could be other reasons I got this behavior.

**Comment by banach-space** [comment]
Hi @mantador , thanks for stopping by! 👋🏻 

Sorry about this. Could you please try:
```
$LLVM_DIR/bin/clang -O0 -emit-llvm -c <source_dir>/inputs/input_for_hello.c -o input_for_hello.bc
```
instead of:
```
$LLVM_DIR/bin/clang -O1 -emit-llvm -c <source_dir>/inputs/input_for_hello.c -o input_for_hello.bc
```
? Thanks!

**Comment by banach-space** [comment]
Sorry, I wasn't awake when I was reading your original post. You included a solution there :) Anyway, I've updated the README. Should be all good now!

Thanks for your help!
