### ISSUE TITLE
MBAAdd Example with new PM

### ISSUE THREAD

**Issue by apwest** [banach-space/llvm-tutor#56]
The MBAAdd pass has a custom command line option specified (`-mba-ratio`), which you show how to use with the legacy pass manager, but you don't show an example of how this is done with the new pass manager. I haven't been able to figure out how to use custom command line options with the new pass manager. Can you provide an example of this?

**Comment by banach-space** [comment]
Hi @apwest , thanks for visiting!

This is a known issue - `opt` does not support command line options in loadable plugins/passes when the new PM is used. At least that used to be the case, but I'm not aware of anyone implementing this (worth double-checking though).

See https://lists.llvm.org/pipermail/llvm-dev/2019-September/134973.html. I do recall others asking similar question on various platforms too.

-Andrzej

**Comment by banach-space** [comment]
Closing as there's been no traffic here. Please re-open if you have more questions!
