### ISSUE TITLE
llvm 14 support

### ISSUE THREAD

**Issue by vjpr** [banach-space/llvm-tutor#57]
Only one change necessary.

Change: https://reviews.llvm.org/D107025

_https://github.com/banach-space/llvm-tutor/blob/main/lib/OpcodeCounter.cpp#L124_

```diff
- llvm::PassBuilder::OptimizationLevel
+ llvm::OptimizationLevel
```

**Comment by banach-space** [comment]
Hi @vjpr 👋🏻 ,

Sorry for the delay, I've been away for a while.

Many thanks for sending this! Also, great timing with LLVM 14 release [schedule](https://llvm.discourse.group/t/llvm-14-0-0-release-schedule/5846) finally available :) I still need to wait for LLVM 14 packages to be available (and for LLVM 14 to be released) before I can update **llvm-tutor**. This link will help greatly in creating a branch for the switch.

Best regards,
Andrzej

**Comment by banach-space** [comment]
FYI: https://github.com/banach-space/llvm-tutor/tree/release_14

**Comment by banach-space** [comment]
I'm waiting for `Homebrew` packages to be available, but that's still in review: https://github.com/Homebrew/homebrew-core/pull/97618. Sorry for the delay.

**Comment by banach-space** [comment]
Closing as we are already on LLVM 15 :)
