### ISSUE TITLE
Can not load legacy hello world pass in LLVM 15

### ISSUE THREAD

**Issue by AmosChenYQ** [banach-space/llvm-tutor#72]
And I also referenced documention on official website, it doesn't work neither, is legacy plugin still supported by LLVM 15?

**Comment by banach-space** [comment]
Sorry about the delay!

> And I also referenced documentation on official website, it doesn't work neither, is legacy plugin still supported by LLVM 15?

TBH, not sure. I though that the legacy PM would be removed in LLVM 15, but that doesn't seem the case. I've asked on [Discourse](https://discourse.llvm.org/t/legacy-pm-in-llvm-15/) and hopefully somebody more knowledgable will help us :)

-Andrzej

**Comment by AmosChenYQ** [comment]
> Sorry about the delay!
> 
> > And I also referenced documentation on official website, it doesn't work neither, is legacy plugin still supported by LLVM 15?
> 
> TBH, not sure. I though that the legacy PM would be removed in LLVM 15, but that doesn't seem the case. I've asked on [Discourse](https://discourse.llvm.org/t/legacy-pm-in-llvm-15/) and hopefully somebody more knowledgable will help us :)
> 
> -Andrzej

Thanks for replying! I think it's ok for me to just use new pass manager.

**Comment by CongzheUalberta** [comment]
IIRC if you'd still like to use the legacy pass manager, you'll have to add `-enable-new-pm=0` to your command line.

**Comment by banach-space** [comment]
Closing this - the discourse post covers this in great detail. Thanks for bringing this up!
