### ISSUE TITLE
[InjectFunCall] how to redirect printf to file

### ISSUE THREAD

**Issue by LuoRongLuoRong** [banach-space/llvm-tutor#73]
I wanna store infomation in a file. But I don't know how to add redirection codes in IR.

`> log.txt` is not a satisfactory solution.

**Comment by banach-space** [comment]
Hi @LuoRongLuoRong , thanks for posting this! This is a generic LLVM question rather than something specific to **llvm-tutor**.  I suggest posting on LLVM's https://discourse.llvm.org/ instead.

-Andrzej
