### ISSUE TITLE
SLPVectorizer didn't vectorize test examples

### ISSUE THREAD

**Issue by khei4** [banach-space/llvm-tutor#86]
for SLP tests, File check commands have lacked. If add it, tests failed. So it might be better to update them. 
like 
```
; RUN: opt -passes=slp-vectorizer,dce -mtriple=x86_64-unknown-linuxgnu -S %s | FileCheck %s
```

If this is intentional for some reasons, close this silently :) 

https://github.com/banach-space/llvm-tutor/blob/main/test/llvm/slp_x86.ll
https://github.com/banach-space/llvm-tutor/blob/main/test/llvm/slp_aarch64.ll

**Comment by banach-space** [comment]
Hi @khei4 , thank you for visiting and for reporting this!

> If this is intentional for some reasons, close this silently :)

No, this is an oversight. I don't remember why I left it like this. Clearly these tests need some love, but I don't have the bandwidth. PRs are welcome ;-)

-Andrzej

**Comment by banach-space** [comment]
Having auto-generated checks is better than no checks at all ;-)
