### ISSUE TITLE
Why is this error 'LT_LLVM_INSTALL_DIR (/include/llvm)' invalid

### ISSUE THREAD

**Issue by sunheyi6** [banach-space/llvm-tutor#95]
![image](https://github.com/banach-space/llvm-tutor/assets/50973219/55529c5b-9906-46c2-9d56-6374817d7f88)
The variable LT_LLVM_INSTALL_DIR already exists and the directory /home/shy/llvm-project/llvm/include/llvm also exists, but it still prompts this error.

**Comment by banach-space** [comment]
You are mixing environment with CMake variables. Please try:
```
cmake -DLT_LLVM_INSTALL_DIR=/home/shy/llvm-project/llvm ..
```

-Andrzej

**Comment by sunheyi6** [comment]
@banach-space I checked, and it seems that the file indeed does not exist.LLVM project was directly pulled from GitHub.
![image](https://github.com/banach-space/llvm-tutor/assets/50973219/4e336fce-d2a7-4b9a-bc58-dc3776bb2d9c)

**Comment by banach-space** [comment]
Please follow README. For example: https://github.com/banach-space/llvm-tutor#installing-llvm-16-on-ubuntu

-Andrzej
